language: python
sudo: false
python:
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - travis_retry pip install -r requirements-dev.txt
  - travis_retry pip install .
script:
  - pytest
after_success:
  - coveralls
env:
    - AWS_DEFAULT_REGION=eu-west-1 AWS_ACCESS_KEY_ID=dummy AWS_SECRET_ACCESS_KEY=dummy BOTO_CONFIG=/dev/null